image: mozilla/sbt:latest
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"
  SBT_CACHE_DIR: "sbt-cache/.ivy/cache"
services:
  - docker:19.03.0-dind
stages:
  - deploy
deploy to dev:
  tags:
    - docker
  stage: deploy
  script:
    - cd gradle-saagie
    - ./gradlew updateJob -PenvironmentName=dev
  only:
    - template_project_scala

deploy to prod:
  tags:
    - docker
  stage: deploy
  script:
    - cd gradle-saagie
    - ./gradlew updateJob -PenvironmentName=prod
  only:
    - none